#!/usr/bin/env sh

# Downloads All Pdfs (dap) from a specific base url

# Usage : dap <base_url_to_download_from>
# This downloads all pdfs to a new directory in the current path
function dap() {
  # mkd dl_pdfs
  mkdir -p "dl_pdfs" && cd "$_" && wget --random-wait -A pdf -m -p -E -k -K -e robots=off -nd -np "$@";

}
