#!/usr/bin/env bash
# Not a sh because OSTYPE, "${@: -1}" are bash/zsh specific

# Merge PDF files
# Usage: `mergepdf input{1,2,3}.pdf output.pdf`
function mergepdf() {
	case $(uname -s) in
		'Linux' | 'Darwin')
			pdfunite "$@"
		;;
		*)
			local arg_arr=("$@")
			local len_arg_arr=${#arg_arr[@]} # compliant with bash < 4.0
			# join usage: `join.py -o output.pdf input{1,2,3}.pdf`
			# output is the last element of the array, equivalent to arr[-1] for bash > 4.0
			/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py --output "${arg_arr[${len_arg_arr}]}" "${arg_arr[@]:0:${len_arg_arr}-1}"
		;;
	esac
}
