#!/usr/bin/env sh

# Create a new directory and enter it
mkd() {
	mkdir -p "$@" && cd "$_" || exit
}

# # Change working directory to the top-most Finder window location
# function cdf() { # short for `cdfinder`
# 	cd "$(osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)')";
# }

# mkd "$@"
