#!/usr/bin/env sh

# Makes a gif from images

# Usage : mkgif <ffmpeg_file_format>
# Core function taken from https://engineering.giphy.com/how-to-make-gifs-with-ffmpeg/
mkgif() {
	if hash ffmpeg 2>/dev/null; then
		ffmpeg -y -i "$@" -filter_complex "[0:v] fps=24,scale=w=480:h=-1,split [a][b];[a] palettegen=stats_mode=single [p];[b][p] paletteuse=new=1" out.gif 2>/dev/null
		if hash gifsicle 2>/dev/null; then
			gifsicle --optimize=3 --delay=3 out.gif >output.gif && rm -f out.gif
		fi
	else
		echo "mkgif needs ffmpeg!"
	fi

}
