#!/usr/bin/env sh

# `s` with no arguments opens the current directory in Sublime Text, otherwise
# opens the given location
s() {
	if [ $# -eq 0 ]; then
		reattach-to-user-namespace subl .
	else
		reattach-to-user-namespace subl "$@"
	fi
}

# s "$@"
