image: ubuntu:latest

stages:
  - build

linux_build:
  stage: build
  before_script:
    - apt-get update >/dev/null
    - apt-get install -y zsh git curl tar make
  script:
    - make ci
  when: always
